### ISSUE TITLE
cryo_fit.run_tests does not work. 

### ISSUE THREAD

**Issue by nwmoriarty** [kimdn/cryo_fit#8]
I hope it wasn't the changes I sent vie pull request.

**Comment by nwmoriarty** [comment]
BTW - There seems to be steps that move files. This makes it difficult to test because they have to be replaced before each run. Maybe that's the problem with this issue.

**Comment by kimdn** [comment]
let me take a look

**Comment by kimdn** [comment]
I ran "python run_tests.py" at "/Users/doonam/bin/phenix-dev-2747/modules/cryo_fit/command_line".

It ran successfully as ...
"	Correlation coefficient change during cryo_fit

	step 0 correlation coefficient: 0.528208
	step 100 correlation coefficient: 0.525634


Step 7
successfully ran
Step 7 finished in 1.38 minutes (wallclock).
Total process finished in 1.79 minutes (wallclock).
********************************************************************************
[]"


I ran with a version of

"commit e71e0d63a5bed73b5d9d949982f05e22817baa81
Author: Doonam in 13inch lanl laptop <doonam.kim@gmail.com>
Date:   Tue Sep 19 14:56:44 2017 -0600

    confirmed to work with tRNA, after Nigel's simplification"

Can I know your input command and error message?
Then I can dig out more, why cryo_fit.run_tests didn't work at your computer.

**Comment by kimdn** [comment]
@nwmoriarty 

I didn't hear a reply for 3 days, so I close it.
I want to welcome you to reopen this issue if you have anything.
